FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

#package.json will be copied to '/app' directory
COPY --chown=node:node ./package.json ./
RUN npm install
#after dependecies are installed we will be copying everything else from our project dir into image
#this copying of the files is not actually needed as in docker-compose file there is volume mounting ''.:/home/node/app', everything from current dir to /home/node/app
COPY --chown=node:node ./ ./

CMD ["npm", "start"]